### ISSUE TITLE
Change host mode

### ISSUE THREAD

**Issue by ahmed-tracxpoint** [dayjaby/zebra-scanner#11]
I have problem in change host mode, 
I implement new function in Scanner cpp and h. and each time I run this function I receive error 112 in status.
//
function body:
std::string inXml = "<inArgs><scannerID>" + scannerID + "</scannerID>"+
                        "<cmdArgs><arg-string>XUA-45001-9</arg-string>" +
                        "<arg-bool>TRUE</arg-bool><arg-bool>FALSE</arg-bool></cmdArgs></inArgs>";

	std::string outXml;
    ::ExecCommand(CMD_DEVICE_SWITCH_HOST_MODE , inXml, outXml, &status);
//

** why and how I can fix this? or how can I set that scanner run at one of this modes automatically:
USB-IBMTT
USB-SNAPI with Imaging
USB-SNAPI without Imaging
 
thanks a lot

**Comment by Sthing** [comment]
Hi @ahmed-tracxpoint 

Are you the same Ahmed as the one who wrote on Zebra's support site, https://supportcommunity.zebra.com/s/question/0D50H000088XT2fSAG/host-variant-switching-ms4717?language=en_US ?
If so, did you get any response?

I have the same issue as you and think the problem lies in the Zebra CoreScanner library for Linux.

Using the linux sample app (/usr/share/zebra-scanner/samples/gui-app/bin/corescanner-gui-app) I get the same error as you. I have tried on Ubuntu 18.04 and a current (buster) Raspberry Pi OS.

Using the windows sample app (C:\Program Files\Zebra Technologies\Barcode Scanners\Scanner SDK\Scanner SDK\Sample Applications\bin\ScannerSDK_SampleAPP_CPP.exe) on the same hardware the CMD_DEVICE_SWITCH_HOST_MODE command works.

**Comment by ahmed-tracxpoint** [comment]
I contact Zebra support and that their response:

""

Hello Ahmed,
Mint Linux version isn't supported from the SDK:
https://www.zebra.com/us/en/support-downloads/software/developer-tools/scanner-sdk-for-linux.html


Ubuntu supports Linux SDK but only this version:
SDK_for_Linux_v4.4.1-11_Debian_Packages_x86_64bit_C11.zip
Debian package for 64bit (C++ 2011 Standard)

Did you download and install this version? Did you install and instructions from here:
https://www.zebra.com/content/dam/zebra_new_ia/en-us/manuals/software/sdk-linux-dev-guide_en.pdf
page 26-31?
But to summarize since your scanner doesn't support Linux SDK, I will suggest you to use Windows SDK and Windows machine.
Inform me if you need anything else.
""

I use MS4717 zebra barcode scanner, I tried by windows its works good.

**Comment by Sthing** [comment]
Thanks for the update @ahmed-tracxpoint .

I use two of the supported linux distributions, so I will try and wrestle their support :-)

/Thing

**Comment by Sthing** [comment]
Hi @ahmed-tracxpoint 

I got a response from Zebra today, that basically said: Too bad - the MS4717 is not on the list of supported devices for the Scanner SDK for Linux.

So I guess the ticket can be closed.

**Comment by ahmed-tracxpoint** [comment]
Yes thanks for responding

**Comment by dayjaby** [comment]
Closing this. I add a list to the front README which devices are supported and which not.

**Comment by Sthing** [comment]
> I add a list to the front README which devices are supported and which not.

Well, MS4717 mostly works. The only thing I cannot get to work is CMD_DEVICE_SWITCH_HOST_MODE. Setting other parameters works fine after manually changing host mode with the barcode from the integration guide.

The devices officially supported by Zebra's library are listed at https://www.zebra.com/us/en/support-downloads/software/developer-tools/scanner-sdk-for-linux.html

**Comment by Sthing** [comment]
According to https://www.zebra.com/content/dam/zebra_new_ia/en-us/software/developer-tools/scanner-sdk-for-linux/release-notes-linux-sdk.pdf the MS4717 should be able to change host mode since "Scanner SDK for Linux" release 4.4.1-16
