### ISSUE TITLE
can we capture images using this package? 

### ISSUE THREAD

**Issue by HawkingRadiation42** [dayjaby/zebra-scanner#29]
basically i want my scanner to scan some barcodes and then shift to image mode to capture images automatically after some barcode scans.  
how can i perform this and is it possible using this python packages.

**Comment by dayjaby** [comment]
In the python wrapper, nothing like this is considered yet. Did you check if the C++ API allows you image capture? In this case, you'd need to add some more code to the wrapper, to expose that to python as well. It shouldn't be too hard, but sadly I don't have a zebra camera right now and can't help you much with that.

**Comment by shrinand1996** [comment]
This is what i want as well. The Linux SDK allows to take pictures for the supported scanners. so yes it works

**Comment by dayjaby** [comment]
@HawkingRadiation42 image capturing done. Check newest example: https://github.com/dayjaby/zebra-scanner/blob/master/examples/cycle_barcode_image_mode.py

**Comment by HawkingRadiation42** [comment]
thankyou

**Comment by nitinss17** [comment]
hello @dayjaby , thank you for this. 

i want the script to capture image and write to disk on hard trigger(physical handle pull), what modifications do i need to do in order to achieve this? if you can drop the code here that would be great! i can copy paste it directly :)

again thank you in advance bcoz this is exactly what i want for my zebra ds3608 scanner .
